src/bookstore_project/bookstore_api/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:book_id>/', views.details, name='details'),
    path('about/', views.about, name='about'),
]

src/bookstore_project/bookstore_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('bookstore/', include('bookstore_api.urls')),
    path('admin/', admin.site.urls),
]

src/bookstore_project/bookstore_api/models.py
from django.db import models


class Book(models.Model):
    EBOOK = 'EB'
    AUDIO = 'AU'
    NEWSPAPER = 'NP'
    FILE_TYPES = (
        (EBOOK, 'eBook'),
        (AUDIO, 'Audio'),
        (NEWSPAPER, 'Newspaper'),
    )
    ENGLISH = 'EN'
    SPANISH = 'SP'
    JAPANESE = 'JP'
    LANGUAGES = (
        (ENGLISH, 'English'),
        (SPANISH, 'Spanish'),
        (JAPANESE, 'Japanese'),
    )
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    pub_date = models.DateField()
    file_type = models.CharField(
        max_length=2,
        choices=FILE_TYPES,
        default=EBOOK
    )
    language = models.CharField(
        max_length=2,
        choices=LANGUAGES,
        default=ENGLISH
    )
    summary = models.CharField(max_length=500)

    def __str__(self):
        return self.title

src/bookstore_project/bookstore_api/forms.py
from django import forms

from .models import Book


class SearchForm(forms.Form):
    search = forms.CharField(
        label='',
        max_length=100,
        widget=forms.TextInput(
            attrs={'placeholder': 'Search'}
        ),
        required=False
    )
    category = forms.ChoiceField(
        label='',
        choices=[(1, 'Title'), (2, 'Author')],
        required=False
    )


class FilterForm(forms.Form):
    file_type = forms.MultipleChoiceField(
        choices=Book.FILE_TYPES,
        widget=forms.CheckboxSelectMultiple(),
        required=False
    )
    language = forms.MultipleChoiceField(
        choices=Book.LANGUAGES,
        widget=forms.CheckboxSelectMultiple(),
        required=False
    )

src/bookstore_project/bookstore_api/views.py
from django.shortcuts import render, get_object_or_404, \
    get_list_or_404
from django.http import Http404

from .models import Book
from .forms import SearchForm, FilterForm

def index(request):
    # Post request
    if request.method == 'POST':
        search_form = SearchForm(request.POST)
        filter_form = FilterForm(request.POST)
        if 'btn-search' in request.POST and search_form.is_valid():
            search = search_form.cleaned_data.get('search')
            category = search_form.cleaned_data.get('category')
            # Section to search
            if category == '1':
                books = list(Book.objects.filter(title__icontains=search))
            elif category == '2':
                books = list(Book.objects.filter(author__icontains=search))
            else:
                books = get_list_or_404(Book)[:5]
        elif 'btn-filter' in request.POST and filter_form.is_valid():
            file_types = filter_form.cleaned_data.get('file_type')
            languages = filter_form.cleaned_data.get('language')
            # No file type filter
            if not file_types:
                for ftype in Book.FILE_TYPES:
                    file_types.append(ftype[0])
            # No language filter
            if not languages:
                for lang in Book.LANGUAGES:
                    languages.append(lang[0])
            # Filter results
            books = []
            for book in Book.objects.all():
                if book.file_type in file_types and book.language in languages:
                    books.append(book)
        else:
            books = get_list_or_404(Book)
    # Get request
    else:
        search_form = SearchForm()
        filter_form = FilterForm()
        books = get_list_or_404(Book)[:10]

    return render(
        request,
        'bookstore_api/index.html',
        {   'Book': Book,
            'books': books,
            'search_form': search_form,
            'filter_form': filter_form,
            'num_results': len(books)
        }
    )

def details(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    return render(
        request,
        'bookstore_api/details.html',
        {
            'book': book
        }
    )

def about(request):
    return render(request, 'bookstore_api/about.html')

src/bookstore_project/bookstore_api/templates/bookstore_api/about.html
{% extends "bookstore_api/base.html" %}

{% block content %}
<div class="row about">
    <div class="col-md-12">
        <h1>About</h1>
        <span>My custom bookstore application utilizing Python/Django/Docker/PostgreSQL/Boostrap.</span>
    </div>
</div>
{% endblock %}

src/bookstore_project/bookstore_api/templates/bookstore_api/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>Bookstore</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'bookstore_api/css/styles.css' %}">

</head>
<body class="tan">
    <div class="container-fluid">
        {% include "bookstore_api/navbar.html" %}

        {% block content %}
        {% endblock %}

        {% include "bookstore_api/footer.html" %}
    </div>

    <script defer src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>
    <script src="http://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="{% static 'bookstore_api/js/scripts.js' %}"></script>
</body>
</html>

src/bookstore_project/bookstore_api/templates/bookstore_api/details.html
{% extends "bookstore_api/base.html" %}

{% block content %}
<div class="row details">
    <div class="col-md-8">
        <li class="d-flex flex-column details-result">
            <span id="grey-text">{{ book.get_file_type_display }}</span>
            <a id="results-title" class="link" href="{% url 'details' book.id %}">{{ book }}</a>
            <span>{{ book.author }}</span>
        </li>

        <h4>Details</h4>

        <hr>

        <div class="row">
            <label class="col-sm-4">Title:</label>
            <span class="col-sm-8">{{ book }}</span>
        </div>

        <div class="row">
            <label class="col-sm-4">Author:</label>
            <span class="col-sm-8">{{ book.author }}</span>
        </div>

        <div class="row">
            <label class="col-sm-4">Language:</label>
            <span class="col-sm-8">{{ book.get_language_display }}</span>
        </div>

        <div class="row">
            <label class="col-sm-4">Published:</label>
            <span class="col-sm-8">{{ book.pub_date }}</span>
        </div>

        <div class="row">
            <label class="col-sm-4">Summary:</label>
            <p class="col-sm-8">{{ book.summary }}</p>
        </div>
    </div>
    <div class="col-md-4 grey">
        <h3>Similar Books</h3>
        <ul>
            <li>Book</li>
            <li>Book</li>
        </ul>
    </div>
</div>
{% endblock %}

src/bookstore_project/bookstore_api/templates/bookstore_api/footer.html
<footer class="green">
    <div class="row footer-links">
        <div class="col-md-12 d-flex justify-content-center">
            <a class="link" href="https://www.linkedin.com/in/derekharmann/"><i class="fab fa-linkedin fa-2x"></i></a>
            <a class="link" href="https://github.com/harmannd"><i class="fab fa-github fa-2x"></i></a>
            <a class="link" href="http://derekharmann.com"><i class="fas fa-link fa-2x"></i></a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 copyright">
            © 2018 Copyright: Derek Harmann
        </div>
    </div>
</footer>

src/bookstore_project/bookstore_api/templates/bookstore_api/index.html
{% extends "bookstore_api/base.html" %}
{% load widget_tweaks %}

{% block content %}
<div class="row">
    <div class="col-md-12 brown">
        <form id="search" action="/bookstore/" method="post">
            {% csrf_token %}
            {{ search_form.non_field_errors }}
            {{ search_form.name_of_field.errors }}
            <div class="input-group input-group-lg">
                {{ search_form.search.errors }}
                {{ search_form.search|add_class:"form-control" }}

                {{ search_form.category.errors }}
                {{ search_form.category|add_class:"form-control" }}

                <div class="input-group-append">
                    <input class="btn tan" type="submit" value="Search" name="btn-search">
                </div>
            </div>
        </form>
    </div>
</div>

<div class="row">
    <div class="col-md-4 form-filter grey">
        <form id="filter" action="/bookstore/" method="post">
            <div class="d-flex justify-content-start flex-column">
                {% csrf_token %}
                {{ filter_form.non_field_errors }}
                {{ filter_form.name_of_field.errors }}

                <a class="filter-button btn btn-secondary" data-toggle="collapse" href="#collapseFileTypes" role="button" aria-expanded="true" aria-controls="collapseFileTypes">
                    File Types
                    <i class="fas fa-angle-down"></i>
                </a>
                <div class="collapse show" id="collapseFileTypes">
                    {{ filter_form.file_type }}
                </div>

                <a class="filter-button btn btn-secondary" data-toggle="collapse" href="#collapseLanguages" role="button" aria-expanded="true" aria-controls="collapseLanguages">
                    Languages
                    <i class="fas fa-angle-down"></i>
                </a>
                <div class="collapse show" id="collapseLanguages">
                    {{ filter_form.language }}
                </div>
            </div>

            <div class="d-flex align-items-end flex-column">
                <input class="filter-submit btn btn-secondary tan" type="submit" value="Filter" name="btn-filter">
            </div>
        </form>
    </div>
    {% include "bookstore_api/results.html" %}
</div>
{% endblock %}

src/bookstore_project/bookstore_api/templates/bookstore_api/navbar.html
<nav class="navbar navbar-light navbar-expand-md d-flex justify-content-center green">
    <a href="{% url 'index' %}" class="navbar-brand mr-auto">Bookstore</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsingNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse" id="collapsingNavbar">
        <ul class="nav navbar-nav w-100 justify-content-end">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
        </ul>
    </div>
</nav>
<div id="nav-image"></div>

src/bookstore_project/bookstore_api/templates/bookstore_api/results.html
<div class="col-md-8">
    <span id="grey-text">{{ num_results }} Results</span>
    <h1>Results</h1>
    <ul>
        {% for book in books %}
            <li class="d-flex flex-column">
                <span id="grey-text">{{ book.get_file_type_display }}</span>
                <a id="results-title" class="link" href="{% url 'details' book.id %}">{{ book }}</a>
                <span>{{ book.author }}</span>
            </li>
            <hr>
        {% endfor %}
    </ol>
</div>